### PR TITLE
Code formatting and tests

### PR DESCRIPTION
**Pull request by ampersarnie**
## Description
To ensure that we're moving forward for `v1.0.0` release and putting ourselves in a better position with subsequent releases, some changes have been required for formatting and general maintenance. Formatting now follows the prettier standard to ensure that formatting is consistent. Jest tests have been added for utilities - though not for all areas this gives us a good start. Huskey has been updated to allow for tests to be run on push as well as linting checks.

I have also removed the `yarn.lock` file to encourage more use of `npm` rather than `yarn` as a standard.

## Change Log
* Added `prettier` and corrected changes resulting from that.
* Added `jest` tests for utilities.
* Updated `husky` and config for v4 -> v7 changes.
* Added test runs to husky `pre-push`.

## Checklist (_if applicable_):
- [x] Meets provided linting standards.

### CODE REVIEW

**Comment by con322** [comment]
Nice pr :) 

I tried running the jest tests and a couple failed. The error looked to be the same for all of them see below.

screenshot

**Comment by ampersarnie** [comment]
> Nice pr :)
> 
> I tried running the jest tests and a couple failed. The error looked to be the same for all of them see below.
> 
> screenshot

Looks like Jest is catching the Cypress tests as well. I'll look into exclusion paths.

**Comment by ampersarnie** [comment]
@con322 This should be fixed now if you would like to review again.

**Comment by con322** [comment]
@ampersarnie failed tests have gone from 13 to 9 but some are still failing.

image

**Review by con322 — APPROVED** [review]

**Comment by ampersarnie** [comment]
Spoke with Connor about the above, issues were differences in setup and Babel transforms on Node v12 providing false reports for coverage. Node v14 and v16 are known to work. Seen the issue also reported here; https://github.com/facebook/jest/issues/10740

**Pull request merged**
